-- MySQL Script generated by MySQL Workbench
-- Thu Feb 15 01:51:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema helpdeskdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema helpdeskdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `helpdeskdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `helpdeskdb` ;

-- -----------------------------------------------------
-- Table `helpdeskdb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdeskdb`.`clientes` (
  `ClienteID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Telefone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ClienteID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helpdeskdb`.`equipamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdeskdb`.`equipamentos` (
  `EquipamentoID` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(100) NULL DEFAULT NULL,
  `Marca` VARCHAR(100) NULL DEFAULT NULL,
  `Modelo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`EquipamentoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helpdeskdb`.`tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdeskdb`.`tecnicos` (
  `TecnicoID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Especialidade` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`TecnicoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helpdeskdb`.`ordensdeservico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdeskdb`.`ordensdeservico` (
  `OrdemID` INT NOT NULL AUTO_INCREMENT,
  `ClienteID` INT NULL DEFAULT NULL,
  `TecnicoID` INT NULL DEFAULT NULL,
  `EquipamentoID` INT NULL DEFAULT NULL,
  `DataAbertura` DATETIME NULL DEFAULT NULL,
  `DataFechamento` DATETIME NULL DEFAULT NULL,
  `Status` ENUM('Aberto', 'Em Andamento', 'Fechado') NULL DEFAULT NULL,
  `DescricaoProblema` TEXT NULL DEFAULT NULL,
  `DescricaoSolucao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`OrdemID`),
  INDEX `ClienteID` (`ClienteID` ASC) VISIBLE,
  INDEX `TecnicoID` (`TecnicoID` ASC) VISIBLE,
  INDEX `EquipamentoID` (`EquipamentoID` ASC) VISIBLE,
  CONSTRAINT `ordensdeservico_ibfk_1`
    FOREIGN KEY (`ClienteID`)
    REFERENCES `helpdeskdb`.`clientes` (`ClienteID`),
  CONSTRAINT `ordensdeservico_ibfk_2`
    FOREIGN KEY (`TecnicoID`)
    REFERENCES `helpdeskdb`.`tecnicos` (`TecnicoID`),
  CONSTRAINT `ordensdeservico_ibfk_3`
    FOREIGN KEY (`EquipamentoID`)
    REFERENCES `helpdeskdb`.`equipamentos` (`EquipamentoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
